language: java
dist: trusty
group: edge
jdk: openjdk8
sudo: required

env:
  global:
    #travis encrypt -r gchq/event-logging-schema GH_USER_AND_TOKEN="*****"
    #where ***** is '<github username>:<github personal access token>'
    #Required for curling the gh api to get the latest release sha
    - secure: "R/Em1F2F3PKSvLfmukEMlJnlG/mR179rCclGBBy6bgcaHkTY1/kaksTb/4JIA2gv4sT9dyBPABwYOot+wIuqsvtDQ0tbB+V5VLqg2qKkFUNCdPi5ooILTlRvltdwNYG54NIFDpqpbBTndoGHQB4fzxuMOG2OQClv/haDxsHtJ+QC3Cf7oNTJxyWxXjPGcBfhjM/s/3AY1yS27vdQGlX4SQ3ZErpPTSYbB1y56jQS1EVFNHL0dI0WGb+FshLbTYknh8b/XcoPkbC53hnRRXchPKdDuOeSSCZhmkL9rOkaLWkfNdZsZUxt1eiWiORzIaP2//TEcWwCmiqZ4WPH8YeWjemyzJjc2ZsYuGIOpZci1+2CTsdN6uq27FLV/T5RpADp/IxOcbvOG7xnJk3bpEB2OG+f+q+xsLmHpmiTVWIes1dI1mkBnWnFZwGQDSTNgFbGypZDcJp+0w941cRCWFNm0D+EOfqce9U1S9rPiulRSX8FsXOBmTxw/30it1ZrW5xQYjWXAFVN2jVZYuV50wHz5HjXUTOabZgDW14UlhVx7+V/nZVZyy78VC/GQw26doYitUKNihBDl+qDgBEOnrIZ/AoB3wUuENvXk+nAIKFQ8mc+gM3mmcGZV8gwGq4FS76U4Z3tGP0+L/FrFPQjzOVgY8XMauf/n+Wjj/F+aswMPy0="

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils
  - sudo apt-get install -y calibre
    #install node
  - nvm install 8.9.3

install: 
  - npm install -g gitbook-cli

script: ./travis.script.sh
    
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _book
    target_branch: gh-pages
    on:
      branch: master
# To generate the api-key for github go to https://github.com/settings/tokens and create a token
# Then do travis 'travis encrypt -r gchq/event-logging-schema <token>'
# where <token> is the token copied from github
  - provider: releases
    api_key:
      secure: TQeb/vUaaDL425Flpf9Sng2WXZYPwY9yWBi3wgHLvao5BQeCZJbKDQy3Ex4j7vky2qfD+xa7ELQ8bcnMwLix6uir0RchoZ872KHxprtiaWVNBFyZ4CElDwC+Rq+ocpLiFxprRIviVNp/Jn9pi7DZh1SjTjoCrktVeC3ahEJwqAYfQNMrL1ZKDe9/ouaba5/h6sw20iNWePr1c+6gGoMgJYxgmlKOCaSdPWs3aIYclGoGOdDTHkq82h/XYJ2S+35wjO2+ks3sq9iZEX39M4s1+k5vg/B1KGX8N7LtqY64oqsms2rpO4a27SxsQ4biGLwKyNqYOropFj1lg99iK1Nx0TeG8knfIUa3gsBSleYfw1dNvfJvm8y4o9yD7ODEDP7WAed0DG8OMWOuI95OGeKIsOEBgvxKPynROSwUpWfNh5uFYD68kQbeIoa99/pqY5cyZvoAPRaWK1cJWl+wbjh79PBJETWAPFGa3kxuwYJ+0ItHjnbr3lmPjwQw3PoObcShNsMrjcezNzTByCpQzPSPZKoVkf39Y2LzQ2Ufv9nVxxDZw11MnN4Gial0bckax4l/rgZXMH1dWYKJEU9a9m646UjPO+xMp/RrvXoFDnz84JaGu9H9x+GYgBQwl6AsvN5bBU1POO0OG0CMT5HoNvtUjh8jXqzuq3UZdbrY9kiAM8E=
    file_glob: true
    file: 
        #The generated schema files
      - event-logging-transformer-main/pipelines/generated/event-logging-*.xsd
        #The fat jar for transforming a source schema
      - event-logging-transformer-main/build/libs/event-logging-transformer*-all.jar
        #The XSLT files used by the transformer
      - event-logging-transformer-main/build/distributions/transformations-*.zip
        #The generated schema documentation
      - event-logging-schema-docs-*.zip
      - event-logging-schema-docs-*.pdf
    skip_cleanup: true
    on:
      tags: true

#clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - node_modules # NPM packages
